[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
API_PORT = "3001"
CLIENT_PORT = "3000"

# Base de données PostgreSQL
POSTGRES_DB = "mona_spark_db"
POSTGRES_USER = "mona_spark_user"
POSTGRES_PASSWORD = "mona_spark_password_cloud_2024"
DATABASE_URL = "postgresql://mona_spark_user:mona_spark_password_cloud_2024@localhost:5432/mona_spark_db"

# Cache Redis
REDIS_HOST = "localhost"
REDIS_PORT = "6379"
REDIS_PASSWORD = "mona_spark_redis_password_cloud_2024"
REDIS_URL = "redis://:mona_spark_redis_password_cloud_2024@localhost:6379"

# Sécurité
JWT_SECRET = "mona_spark_jwt_secret_key_cloud_2024_secure"
ENCRYPTION_KEY = "mona_spark_encryption_key_cloud_2024_secure"

# APIs Streaming
TWITCH_CLIENT_ID = "your_twitch_client_id"
TWITCH_CLIENT_SECRET = "your_twitch_client_secret"
YOUTUBE_API_KEY = "your_youtube_api_key"
TIKTOK_API_KEY = "your_tiktok_api_key"

# Email
SMTP_HOST = "smtp.gmail.com"
SMTP_USER = "your_email@gmail.com"
SMTP_PASS = "your_email_password"
SMTP_PORT = "587"

# URLs
NEXT_PUBLIC_API_URL = "https://mona-spark-api.railway.app"
NEXT_PUBLIC_APP_URL = "https://mona-spark-client.railway.app"

# Monitoring
ENABLE_METRICS = "true"
ENABLE_LOGGING = "true"
LOG_LEVEL = "info" 