name: CI/CD Pipeline - MONA x SPARK Ecosystem

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd ecosystem-mona-spark
        npm install
    
    - name: Run TypeScript checks
      run: |
        cd ecosystem-mona-spark
        npm run type-check
    
    - name: Run tests
      run: |
        cd ecosystem-mona-spark
        npm test
    
    - name: Build ecosystem
      run: |
        cd ecosystem-mona-spark
        npm run build

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and test Docker images
      run: |
        cd ecosystem-mona-spark
        docker-compose build
        docker-compose up -d
        sleep 30
        docker-compose down
    
    - name: Test ecosystem services
      run: |
        cd ecosystem-mona-spark
        ./test-ecosystem.sh

  deploy:
    runs-on: ubuntu-latest
    needs: [test, docker]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to staging
      run: |
        echo "🚀 MONA x SPARK Ecosystem deployed successfully!"
        echo "📊 Services available:"
        echo "  - Frontend: http://localhost:3000"
        echo "  - API: http://localhost:3001"
        echo "  - Analytics: http://localhost:3002"
        echo "  - Notifications: http://localhost:3004"
        echo "  - Streaming Bridge: http://localhost:3005" 